### ISSUE TITLE
Not compatible with Webpack 5

### ISSUE THREAD

**Issue by ttencate** [mayakwd/webpack-texture-packer#2]
This plugin looks great, but unfortunately it's not compatible with Webpack 5 (nor does it claim to be). When I try it anyway, this happens:

```
[webpack-cli] TypeError: Cannot add property texturePackerEmitAtlas, object is not extensible
    at WebpackTexturePackerPlugin.apply (/tmp/foo/node_modules/webpack-texture-packer/dist/plugin/WebpackTexturePackerPlugin.js:29:47)
    at createCompiler (/tmp/foo/node_modules/webpack/lib/webpack.js:74:12)
    at create (/tmp/foo/node_modules/webpack/lib/webpack.js:127:16)
    at webpack (/tmp/foo/node_modules/webpack/lib/webpack.js:135:47)
    at WebpackCLI.f [as webpack] (/tmp/foo/node_modules/webpack/lib/index.js:55:16)
    at WebpackCLI.createCompiler (/tmp/foo/node_modules/webpack-cli/lib/webpack-cli.js:2053:29)
    at async WebpackCLI.buildCommand (/tmp/foo/node_modules/webpack-cli/lib/webpack-cli.js:2173:20)
    at async Command.<anonymous> (/tmp/foo/node_modules/webpack-cli/lib/webpack-cli.js:850:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/tmp/foo/node_modules/webpack-cli/lib/webpack-cli.js:1495:13)
```

**Comment by mayakwd** [comment]
Fixed in version 1.0.0
